### ISSUE TITLE
Jdump_joomla4 troubles

### ISSUE THREAD

**Issue by dpardons** [saman222/jdump_joomla4#1]
Hi
I tried your plugin on J4 4.1.3 with php 7.4.19
1) On zip installation, joomla declares "Internal error server".
2) I tried to install separately the component and the  plugin with manual activation of the plugin. No problem detected.

BUT
the jdump programs does not seem to intercept jdump statement and the popup never appears (popup is enabled).

Some idea, some help?

Regards

Daniel

**Comment by saman222** [comment]
Hi
>BUT
the jdump programs does not seem to intercept jdump statement and the popup never appears (popup is enabled).

Is it possible get more detail about your problem? Also describe the steps to implement the problem.

**Comment by dpardons** [comment]
Hi
Sorry, I was away of my PC for some time.

I tried to use jdump as usual on joomla 3 with the popup window.
Working with Laragon localhost J4 4.1.3 with php 7.4.20, template j51_nina with joomla debug enabled and max errors ON

1) Downloading the package from github and manual install: error on install
------
An error has occurred.

0 Argument 1 passed to pkg_DumpInstallerScript::__construct() must be an instance of JAdapterInstance, instance of Joomla\CMS\Installer\Adapter\PackageAdapter given, called in C:\laragon\www\j51_nina\libraries\src\Installer\InstallerAdapter.php on line 1021 

Call stack
--
# | Function | Location
1 | () | JROOT\tmp\install_6288f6ad36a85\jdump_joomla4-main\pkg_script.php:12
2 | pkg_DumpInstallerScript->__construct() | JROOT\libraries\src\Installer\InstallerAdapter.php:1021
3 | Joomla\CMS\Installer\InstallerAdapter->setupScriptfile() | JROOT\libraries\src\Installer\InstallerAdapter.php:757
4 | Joomla\CMS\Installer\InstallerAdapter->install() | JROOT\libraries\src\Installer\Installer.php:521
5 | Joomla\CMS\Installer\Installer->install() | JROOT\administrator\components\com_installer\src\Model\InstallModel.php:206
6 | Joomla\Component\Installer\Administrator\Model\InstallModel->install() | JROOT\administrator\components\com_installer\src\Controller\InstallController.php:50
7 | Joomla\Component\Installer\Administrator\Controller\InstallController->install() | JROOT\libraries\src\MVC\Controller\BaseController.php:735
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
9 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:389
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:143
11 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:186
12 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:278
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
14 | require_once() | JROOT\administrator\index.php:32
---
2) Unzipping the package and installing separately the component and plugin: installation successful
3) Manual enabling of the plugin: OK
4) Testing admin component access: all seems OK except 
Button Options allows parametrization and button Popup opens the popup window.
May be, it could be useful to adapt the comments on the main admin panel.

5) Addition of dump statement in the mod_geekmasthead default.php file

$moduleid = 'geek-masthead-' . $module->id;
echo $moduleid;
dump($moduleid, 'Module ID');

Running the page does not start the dump popup window but displays the following in the module position:
geek-masthead-140 (echo)
^ "geek-masthead-140"
^ "Module ID"

6) When using the dump statement dumpSysinfo(); the following error is displayed:
The requested page can't be found.
An error has occurred while processing your request.
0 Class 'JArrayHelper' not found

I corrected the problem by edition of the sysinfo.php file
- replacing line 12   jimport( 'joomla.utilities.array' ); by use Joomla\Utilities\ArrayHelper; 
- and correcting line 35 JArrayHelper::fromObject( $jconf ); by  ArrayHelper::fromObject( $jconf ); 
Now the sysinfo displays correctly but once more inline in the module position and not on the popup window.

7) Is this inline display the wanted display or are you still trying to work with the popup window?

Waiting for comments or correction.
Regards
Daniel

**Comment by saman222** [comment]
hi @dpardons 
Use the dumpp() function to display pop-ups because the dump() function confilict with the Joomla 4 kernel function.

**Comment by dpardons** [comment]
Hi
Not working.
I stop investigations.
Regards
Daniel
